config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard do
    get 'players', to: 'players#index'
  end
  devise_for :users
  
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  validates :name, presence: true
  validates :nickname, uniqueness: true, presence: true
  validates :status, presence: true
  validates :position, presence: true

  enum status: { titular: 0, reserva: 1 }
  enum position: { goleiro: 0, linha: 1 }

  ## helpfull commands
  # Player.where(status: 0, position: 1).map(&:linha?)
  # Player.where(status: 0, position: 1).map(&:nickname)

  # Player.where(status: 0, position: 0).map(&:goleiro?)
  # Player.where(status: 0, position: 0).map(&:nickname)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /\A[a-z0-9._]+@[a-z0-9]+\.[a-z]{2,3}+(\.[a-z]{2,3})?(\.[a-z]{2})?\z/

  validates :name, presence: true
  validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name])
  end
end

app/controllers/dashboard/players_controller.rb
class Dashboard::PlayersController < DashboardController
  def index
    @players = Player.where(status: 0).order(:name)
    # render json: @players.as_json
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # skip_before_action :authenticate_user!, only: :index
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/players_helper.rb
module Dashboard::PlayersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/players/index.html.erb
<div class="table-responsive table-responsive-sm">
  <table class="table table-bordered border-primary">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Apelido</th>
        <th scope="col">Camisa</th>
        <th scope="col">Situação</th>
        <th scope="col">Gols</th>
        <th scope="col">Posição</th>
      </tr>
    </thead>
    <tbody>
      <% @players.each do |player| %>
        <tr>
          <td><%= player.name %></td>
          <td><%= player.nickname %></td>
          <td><%= player.shirt_number %></td>
          <td><%= player.status %></td>
          <td><%= player.score_goal %></td>
          <td><%= player.position %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meu Racha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meu Racha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render partial: 'shared/sidebar' %>
  </body>
</html>

app/views/shared/_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Meu Racha</a>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to 'Cadastrar partidas', dashboard_players_path, method: :get, class: "nav-link active" %>
      </li>
    </ul>
    <div class="d-flex">
      <% unless user_signed_in? %>
        <%= link_to 'Entrar', new_user_session_path, method: :get, class: "btn btn-dark" %>
      <% else %>
        <%= link_to 'Sair', destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="container-fluid overflow-hidden">
	<div class="row vh-100 overflow-auto">
			<div class="col-12 col-sm-3 col-xl-2 px-sm-2 px-0 bg-dark d-flex sticky-top">
					<div class="d-flex flex-sm-column flex-row flex-grow-1 align-items-center align-items-sm-start px-3 pt-2 text-white">
              <%= link_to root_path, method: :get, class: "d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto text-white text-decoration-none" do %>
                <i class="fs-4 bi-house"></i><span class="ms-1 d-none d-sm-inline">Home</span>
              <% end %>
							<ul class="nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1 flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start" id="menu">
									<li class="dropdown">
											<a href="#" class="nav-link dropdown-toggle px-sm-0 px-2" id="dropdown" data-bs-toggle="dropdown" aria-expanded="false">
													<i class="fs-5 bi-grid"></i><span class="ms-1 d-none d-sm-inline">Partidas</span>
											</a>
											<ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdown">
													<li><a class="dropdown-item" href="#">Nova Partida</a></li>
													<li><a class="dropdown-item" href="#">Relatórios</a></li>
											</ul>
									</li>
									<li>
                    <%= link_to dashboard_players_path, method: :get, class: "nav-link px-sm-0 px-2" do %>
                      <i class="fs-5 bi-people"></i><span class="ms-1 d-none d-sm-inline">Jogadores</span>
                    <% end %>
									</li>
							</ul>
							<div class="dropdown py-sm-4 mt-sm-auto ms-auto ms-sm-0 flex-shrink-1">
									<a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
											<img src="https://github.com/jesherdevsk8.png" alt="hugenerd" width="28" height="28" class="rounded-circle">
											<span class="d-none d-sm-inline mx-1"><%= current_user&.name.split[0] %></span>
									</a>
									<ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                    <li><a class="dropdown-item" href="#">Settings</a></li>
											<li>
												<%= link_to 'Editar', edit_user_registration_path, method: :get, class: "dropdown-item" %>
											</li>
											<li><hr class="dropdown-divider"></li>
											<li>
												<%= link_to 'Sair', destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "dropdown-item" %>
											</li>
                  </ul>                  
							</div>
					</div>
			</div>
			<div class="col d-flex flex-column h-100">
        <main class="row">
          <div class="col pt-4">
            <%= yield %>
          </div>
        </main>
			</div>
	</div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>